#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/mydb2
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental3?allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 6
  cache:
    type: redis
    redis:
      cache-null-values: true
hbase:
   zookeeper:
     quorum: 127.0.0.1:2181